from enum import StrEnum


class EventMilestoneType(StrEnum):
    INVITATION_CREATED = "INVITATION_CREATED"
    INVITATION_APPROVED = "INVITATION_APPROVED"
    TICKET_GENERATED = "TICKET_GENERATED"
    TICKET_REVOKED = "TICKET_REVOKED"
    TICKET_SCANNED = "TICKET_SCANNED"
